In [3]:
import torch
torch.__version__

'2.9.0'

In [9]:
torch.backends.mps.is_available()

True

In [10]:
torch.cuda.is_available()

False

In [11]:
# create tensors

In [13]:
a = torch.empty(2,2)

In [14]:
type(a)

torch.Tensor

In [15]:
torch.zeros(2,2)

tensor([[0., 0.],
        [0., 0.]])

In [16]:
torch.ones(2,2)

tensor([[1., 1.],
        [1., 1.]])

In [17]:
torch.rand(2,2)

tensor([[0.8542, 0.2268],
        [0.7384, 0.7921]])

In [18]:
torch.manual_seed(25)
torch.rand(2,2)

tensor([[0.7518, 0.1929],
        [0.0629, 0.9118]])

In [19]:
torch.manual_seed(25)
torch.rand(2,2)

tensor([[0.7518, 0.1929],
        [0.0629, 0.9118]])

In [20]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
torch.linspace(1,10,19)

tensor([ 1.0000,  1.5000,  2.0000,  2.5000,  3.0000,  3.5000,  4.0000,  4.5000,
         5.0000,  5.5000,  6.0000,  6.5000,  7.0000,  7.5000,  8.0000,  8.5000,
         9.0000,  9.5000, 10.0000])

In [25]:
torch.eye(2)

tensor([[1., 0.],
        [0., 1.]])

In [26]:
torch.full((2,2),25)

tensor([[25, 25],
        [25, 25]])

In [28]:
a.shape

torch.Size([2, 2])

In [30]:
torch.empty_like(a)

tensor([[0., 0.],
        [0., 0.]])

In [31]:
a.dtype

torch.float32

In [33]:
b = torch.tensor([1.2,1.3], dtype = torch.int32)

In [36]:
b

tensor([1, 1], dtype=torch.int32)

In [34]:
b.to(torch.float32)

tensor([1., 1.])

In [38]:
torch.rand_like(a, dtype = torch.float32)

tensor([[0.3828, 0.2990],
        [0.5933, 0.2911]])

In [40]:
# Maths is same as regular algebra

In [43]:
c = torch.tensor([1.1,2.5,3.7])

In [44]:
torch.round(c)

tensor([1., 2., 4.])

In [45]:
torch.ceil(c)

tensor([2., 3., 4.])

In [47]:
torch.clamp(c, min = 2 , max = 3)

tensor([2.0000, 2.5000, 3.0000])

In [48]:
torch.max(c)

tensor(3.7000)

In [49]:
torch.prod(c)

tensor(10.1750)

In [51]:
torch.mean(c)

tensor(2.4333)

In [50]:
torch.std(c)

tensor(1.3013)

In [52]:
torch.var(c)

tensor(1.6933)

In [53]:
torch.argmax(c)

tensor(2)

In [55]:
d = torch.tensor([[1,2,3],
                 [2,3,4]])

In [57]:
e = torch.tensor([1,2])

In [59]:
torch.matmul(e, d)

tensor([ 5,  8, 11])

In [66]:
torch.transpose(d,0,1)

tensor([[1, 2],
        [2, 3],
        [3, 4]])

In [69]:
torch.det(a)

tensor(0.)

In [71]:
f = torch.tensor([0,5])

In [72]:
e > f

tensor([ True, False])

In [74]:
e < f

tensor([False,  True])

In [75]:
torch.log(f)

tensor([  -inf, 1.6094])

In [79]:
torch.softmax(f.to(torch.float32) , dim = 0)

tensor([0.0067, 0.9933])

In [80]:
#inplace operation 
e.add_(f)

tensor([1, 7])

In [81]:
torch.relu_(e)

tensor([1, 7])

In [82]:
f = e.clone()

In [83]:
f

tensor([1, 7])

In [84]:
# tensor operations on GPU

In [85]:
device = torch.device('mps')

In [86]:
torch.rand((2,3), device = device)

tensor([[0.2196, 0.1501, 0.3529],
        [0.8805, 0.4401, 0.5346]], device='mps:0')

In [91]:
g = f.to(device)
g

tensor([1, 7], device='mps:0')

In [94]:
h = torch.rand(3,3)
h

tensor([[0.5181, 0.9726, 0.8813],
        [0.0056, 0.3056, 0.9384],
        [0.7949, 0.4399, 0.1766]])

In [95]:
h.reshape(1,9)

tensor([[0.5181, 0.9726, 0.8813, 0.0056, 0.3056, 0.9384, 0.7949, 0.4399, 0.1766]])

In [96]:
h.flatten()

tensor([0.5181, 0.9726, 0.8813, 0.0056, 0.3056, 0.9384, 0.7949, 0.4399, 0.1766])

In [97]:
i = torch.rand(226,226,3)
i.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [102]:
j = torch.rand(1,4)
j.squeeze(0).shape

torch.Size([4])

In [109]:
# pytorch -> np

In [105]:
import numpy
b = b.numpy()

In [107]:
type(b)

numpy.ndarray

In [108]:
# np -> pytorch 

In [110]:
b = torch.from_numpy(b)

In [111]:
type(b)

torch.Tensor

In [113]:
# Autograd

In [123]:
# eg1

In [116]:
x = torch.tensor(3., requires_grad = True)
y = x ** 2

In [117]:
y

tensor(9., grad_fn=<PowBackward0>)

In [118]:
y.backward()

In [121]:
x.grad

tensor(6.)

In [122]:
#eg2

In [128]:
x = torch.tensor(3., requires_grad = True)
y = x ** 2
z = torch.sin(y)

In [129]:
z.backward()
x.grad

tensor(-5.4668)

In [131]:
#eg3 (NN)

In [194]:
y_true.shape

torch.Size([2])

In [220]:
import torch.nn as nn
L = nn.CrossEntropyLoss()
# y_true = torch.tensor([[1.,0.]])
y_true = torch.tensor([1])

x = torch.tensor([1.,2.])
w1 = torch.randn([2,3], requires_grad = True)
b1 = torch.ones([1,3], requires_grad = True)
h = torch.sigmoid((torch.matmul(x, w1)) + b1)
w2 = torch.randn([3,2], requires_grad = True)
b2 = torch.ones([1,2], requires_grad = True)
y = (torch.matmul(h, w2)) + b2
loss = L(y, y_true)

In [221]:
y

tensor([[-1.9341,  0.8452]], grad_fn=<AddBackward0>)

In [222]:
y_true.shape

torch.Size([1])

In [223]:
y.shape

torch.Size([1, 2])

In [224]:
loss.backward()
w1.grad

tensor([[-0.0032, -0.0016, -0.0107],
        [-0.0063, -0.0033, -0.0215]])

In [225]:
w2.grad

tensor([[ 0.0398, -0.0398],
        [ 0.0016, -0.0016],
        [ 0.0543, -0.0543]])

In [226]:
b1.grad

tensor([[-0.0032, -0.0016, -0.0107]])

In [227]:
b2.grad

tensor([[ 0.0584, -0.0584]])

In [229]:
#verify
print(torch.softmax(y, dim=1))

tensor([[0.0584, 0.9416]], grad_fn=<SoftmaxBackward0>)


In [231]:
#clear gradients to handle the accumulation
w1.grad.zero_()
w2.grad.zero_()
b1.grad.zero_()
b2.grad.zero_()

tensor([[0., 0.]])

In [240]:
#when doing inference (not training)
#define a new set of variable (this is one way to do it, we could also use "w.requires_grad_ = False"
#or use:-
# with torch.no_grad():
#     y = w*x + b

w11 = w1.detach()

In [241]:
w11

tensor([[-0.4371, -1.3000,  0.5875],
        [ 0.0958, -1.6288,  0.4909]])