In [4]:
import torch
import torch.nn as nn
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [5]:
df = pd.read_csv("/Users/animeshsingh/Desktop/Datasets/breast_cancer.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [6]:
df = df.drop(columns = ["id","Unnamed: 32"])

In [7]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [8]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size = 0.15)

In [9]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[-0.33263869, -0.77800909, -0.32431141, ..., -0.19950537,
         1.05769741, -0.15023283],
       [-0.44969614, -0.55525676, -0.51284052, ..., -1.3218597 ,
        -1.61788748, -1.23376203],
       [ 0.79225484,  0.06988688,  0.69747491, ..., -0.45714505,
        -0.61782205, -1.34635097],
       ...,
       [ 0.26406879,  1.44472383,  0.16462122, ..., -1.30426554,
        -2.19497442, -1.60720059],
       [ 0.92073253,  0.70940163,  0.94608472, ...,  0.58993687,
         0.26748178, -0.50360604],
       [-0.66097056, -0.38519853, -0.64957592, ..., -0.20256523,
        -0.69815517, -0.35144376]], shape=(483, 30))

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
# numpy to tensors

In [13]:
X_train = torch.from_numpy(X_train)
X_test = torch.from_numpy(X_test)
y_train = torch.from_numpy(y_train)
y_test = torch.from_numpy(y_test)

In [14]:
# NN

In [15]:
class NN():
    def __init__(self, X):
        self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
        self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

    def fwd(self, X):
        z = torch.matmul(X, self.weights) + self.bias
        y = torch.sigmoid(z)
        return y

In [16]:
lr = 0.1
epochs = 500

In [17]:
model = NN(X_train)
model.weights

tensor([[0.1688],
        [0.1042],
        [0.8560],
        [0.1344],
        [0.4562],
        [0.1544],
        [0.9976],
        [0.3853],
        [0.6802],
        [0.5934],
        [0.6818],
        [0.7690],
        [0.0402],
        [0.5748],
        [0.2681],
        [0.0791],
        [0.4027],
        [0.6304],
        [0.9034],
        [0.2280],
        [0.6741],
        [0.5989],
        [0.0157],
        [0.9375],
        [0.2483],
        [0.4577],
        [0.1351],
        [0.1778],
        [0.9646],
        [0.4632]], dtype=torch.float64, requires_grad=True)

In [18]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [25]:
for epoch in range(epochs):
    # fwd
    y = model.fwd(X_train)
    y_train = y_train.to(torch.float64)
    y = y.flatten()
    # loss
    bce = nn.BCELoss()
    loss = bce(y, y_train)
    # back
    loss.backward()
    # grad = model.weights.grad
    # update
    with torch.no_grad():
        model.weights -= lr * model.weights.grad
        model.bias -= lr * model.bias.grad

    model.weights.grad.zero_()
    model.bias.grad.zero_()

    print(f'epoch: {epoch + 1}, loss: {loss.item()}')

epoch: 1, loss: 0.46274975406766133
epoch: 2, loss: 0.4467691657864873
epoch: 3, loss: 0.4313626758717461
epoch: 4, loss: 0.41650910650436773
epoch: 5, loss: 0.4021830269664054
epoch: 6, loss: 0.38835601374903733
epoch: 7, loss: 0.3749986764306566
epoch: 8, loss: 0.3620827423511789
epoch: 9, loss: 0.34958271255125123
epoch: 10, loss: 0.33747688092711586
epoch: 11, loss: 0.32574778053160136
epoch: 12, loss: 0.3143822124717613
epoch: 13, loss: 0.3033710196529821
epoch: 14, loss: 0.2927087151837535
epoch: 15, loss: 0.28239302055769305
epoch: 16, loss: 0.27242432946579753
epoch: 17, loss: 0.26280509194599305
epoch: 18, loss: 0.2535391123572999
epoch: 19, loss: 0.24463076714388773
epoch: 20, loss: 0.2360841709105204
epoch: 21, loss: 0.22790234430545386
epoch: 22, loss: 0.22008645648959718
epoch: 23, loss: 0.2126352212564588
epoch: 24, loss: 0.20554451466652726
epoch: 25, loss: 0.19880725438908176
epoch: 26, loss: 0.1924135429523035
epoch: 27, loss: 0.18635103836662448
epoch: 28, loss: 0.180

In [26]:
with torch.no_grad():
    y = model.fwd(X_test)
    y = (y > 0.5).float()

accuracy = (y == y_test).float().mean()
accuracy

tensor(0.5189)

# Using NN module and more

In [27]:
class NN1(nn.Module):
    # def __init__(self,n):
    #     super().__init__()
    #     self.linear1 = nn.Linear(n, 3)
    #     self.relu = nn.ReLU()
    #     self.linear2 = nn.Linear(3,1)
    #     self.sigmoid = nn.Sigmoid()

    # def fwd(self, X):
    #     out = self.linear1(X)
    #     out = self.relu(out)
    #     out = self.linear2(out)
    #     out = self.sigmoid(out)
    #     return out

    def __init__(self, n):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n, 50),
            nn.ReLU(),
            nn.Linear(50,10),
            nn.ReLU(),
            nn.Linear(10,1),
            nn.Sigmoid()
        )
    
    def forward(self, vars):
        out = self.net(vars)
        return out

In [28]:
# !pip install torchinfo
X_train = X_train.float()
y_train = y_train.float()

In [29]:
model = NN1(30)
optimizer = torch.optim.SGD(model.parameters(), lr = lr)

for epoch in range(epochs):
    # fwd
    y = model(X_train)
    y = y.flatten()
    
    # loss
    bce = nn.BCELoss()
    loss = bce(y, y_train)
    
    # back
    optimizer.zero_grad()
    loss.backward()
    
    # grad = model.weights.grad
    # update
    optimizer.step()

    print(f'epoch: {epoch + 1}, loss: {loss.item()}')

epoch: 1, loss: 0.6912309527397156
epoch: 2, loss: 0.6804588437080383
epoch: 3, loss: 0.6705710887908936
epoch: 4, loss: 0.6612938046455383
epoch: 5, loss: 0.6524397730827332
epoch: 6, loss: 0.6437876224517822
epoch: 7, loss: 0.6351721286773682
epoch: 8, loss: 0.6264617443084717
epoch: 9, loss: 0.6174744963645935
epoch: 10, loss: 0.6079574227333069
epoch: 11, loss: 0.5978975892066956
epoch: 12, loss: 0.5872682929039001
epoch: 13, loss: 0.5760455131530762
epoch: 14, loss: 0.5643482208251953
epoch: 15, loss: 0.5521063804626465
epoch: 16, loss: 0.5392526984214783
epoch: 17, loss: 0.5258521437644958
epoch: 18, loss: 0.5120048522949219
epoch: 19, loss: 0.4976442754268646
epoch: 20, loss: 0.48285406827926636
epoch: 21, loss: 0.4676997661590576
epoch: 22, loss: 0.4522111117839813
epoch: 23, loss: 0.4364490509033203
epoch: 24, loss: 0.4204796552658081
epoch: 25, loss: 0.40440699458122253
epoch: 26, loss: 0.3883374035358429
epoch: 27, loss: 0.37235161662101746
epoch: 28, loss: 0.356596231460571

In [33]:
samp = torch.rand(5)
model = NN1(5)
y = model.forward(samp)
y

tensor([0.5113], grad_fn=<SigmoidBackward0>)

In [34]:
samp.shape

torch.Size([5])

In [35]:
y.shape

torch.Size([1])

In [36]:
print(X_train.dtype)

torch.float32


# Dataloader

In [37]:
X_train.shape

torch.Size([483, 30])

In [38]:
y_train.shape

torch.Size([483])

In [39]:
from torch.utils.data import DataLoader, Dataset

In [40]:
class Datalao(Dataset):
    def __init__(self, X, y):
        self.X = X
        self.y = y

    def __len__(self):
        return self.X.shape[0]

    def __getitem__(self, index):
        return self.X[index], self.y[index]

In [41]:
train_data = Datalao(X_train, y_train)
test_data = Datalao(X_test, y_test)

In [42]:
len(train_data)

483

In [43]:
train_data[0]

(tensor([-0.3326, -0.7780, -0.3243, -0.3950, -0.6885, -0.1753, -0.4994, -0.4635,
         -0.1464, -0.0784, -0.7143, -0.8223, -0.6124, -0.5480, -0.5890, -0.5636,
         -0.5494, -0.6990,  0.0410, -0.7168, -0.3533, -0.6132, -0.2840, -0.4010,
         -0.0477,  0.0243, -0.2974, -0.1995,  1.0577, -0.1502]),
 tensor(0.))

In [44]:
dataloader = DataLoader(train_data, batch_size = 10, shuffle = True, drop_last = False)

In [45]:
for batch_X, batch_y in dataloader:
    print(batch_X)
    print(batch_y)
    print(".."*125)

tensor([[ 1.6402,  0.7142,  1.5925,  1.7588,  0.1312, -0.0307,  0.7365,  1.1926,
         -0.8565, -1.2450,  1.3393, -0.3673,  1.6037,  1.7084, -0.1998, -0.3756,
          0.0536,  0.5455, -0.8606, -0.6766,  2.3017,  0.8956,  2.3783,  2.6641,
          0.8389,  0.4203,  1.2873,  1.9057, -0.2227, -0.4306],
        [-0.0557, -0.7085, -0.1263, -0.1603, -0.6416, -0.9386, -0.9231, -0.7218,
         -1.4290, -0.5672, -0.5633,  0.2731, -0.5869, -0.4514, -0.4846, -1.0019,
         -0.8650, -0.9507, -0.6340, -0.6437, -0.2230,  0.0130, -0.2968, -0.3126,
         -0.7525, -0.9886, -1.0514, -0.8978, -0.8883, -0.7104],
        [ 2.6109,  1.8687,  2.5662,  2.9396, -0.0975,  1.2140,  1.3248,  1.9345,
          0.3282,  0.0244,  2.4713, -0.4663,  2.3371,  2.7311, -0.2217,  0.1772,
          0.4081,  0.8638, -0.5785, -0.2903,  3.0647,  1.5001,  2.9487,  3.6181,
          0.7014,  1.0622,  1.5037,  2.2193,  0.3265,  0.1613],
        [-0.3069, -1.1828, -0.3102, -0.3890, -0.1309, -0.0886, -0.6438, -0.7193

In [46]:
class NN1(nn.Module):
    def __init__(self, n):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n, 50),
            nn.ReLU(),
            nn.Linear(50,10),
            nn.ReLU(),
            nn.Linear(10,1),
            nn.Sigmoid()
        )
    
    def forward(self, vars):
        out = self.net(vars)
        return out

In [47]:
model = NN1(30)
optimizer = torch.optim.SGD(model.parameters(), lr = lr)
epochs = 100
for epoch in range(epochs):
    for batch_X, batch_y in dataloader:
        # fwd
        y = model(batch_X)
        y = y.flatten()
        
        # loss
        bce = nn.BCELoss()
        loss = bce(y, batch_y)
        
        # back
        optimizer.zero_grad()
        loss.backward()
        
        # grad = model.weights.grad
        # update
        optimizer.step()
    
    print(f'epoch: {epoch + 1}, loss: {loss.item()}')

epoch: 1, loss: 0.23425771296024323
epoch: 2, loss: 0.08684676140546799
epoch: 3, loss: 0.07997328788042068
epoch: 4, loss: 0.017640432342886925
epoch: 5, loss: 0.002951130038127303
epoch: 6, loss: 0.005326279904693365
epoch: 7, loss: 0.0230911523103714
epoch: 8, loss: 4.218657340970822e-05
epoch: 9, loss: 0.8055124878883362
epoch: 10, loss: 0.0008612559176981449
epoch: 11, loss: 2.777666668407619e-05
epoch: 12, loss: 0.0006499275332316756
epoch: 13, loss: 0.0005734793958254158
epoch: 14, loss: 0.000333952164510265
epoch: 15, loss: 0.47776177525520325
epoch: 16, loss: 0.00013964319077786058
epoch: 17, loss: 0.00609651580452919
epoch: 18, loss: 0.007417734246701002
epoch: 19, loss: 0.0016035815933719277
epoch: 20, loss: 0.01871153526008129
epoch: 21, loss: 1.0409940841782372e-05
epoch: 22, loss: 0.00010761552402982488
epoch: 23, loss: 0.0002915022778324783
epoch: 24, loss: 0.0003579398326110095
epoch: 25, loss: 0.00020078547822777182
epoch: 26, loss: 9.617943760531489e-06
epoch: 27, los

# ANN

In [48]:
df2 = pd.read_csv("/Users/animeshsingh/Desktop/Datasets/Fashion_MNIST/fashion-mnist_train.csv")
df2.head()

,label,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783,pixel784
0,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,9,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6,0,0,0,0,0,0,0,5,0,...,0,0,0,30,43,0,0,0,0,0
3,0,0,0,0,1,2,0,0,0,0,...,3,0,0,0,0,1,0,0,0,0
4,3,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0


In [49]:
X = df2.iloc[:,1:].values
y = df2.iloc[:,0].values

In [50]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 40, test_size = 0.2)

In [51]:
X_train = X_train/255.0
X_test = X_test/255.0

In [52]:
X_train.dtype

dtype('float64')

In [53]:
class Datass(Dataset):
    def __init__(self, X, y):
        self.X = torch.tensor(X, dtype = torch.float32)
        self.y = torch.tensor(y, dtype = torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

In [54]:
train = Datass(X_train, y_train)

In [55]:
len(train)

48000

In [56]:
test = Datass(X_test, y_test)

In [57]:
len(test)

12000

In [58]:
train_load = DataLoader(train, batch_size = 1200, num_workers = 0, shuffle = True, pin_memory = True)
test_load = DataLoader(test, batch_size = 1200, shuffle = False, pin_memory = True)

In [59]:
class ANN(nn.Module):
    def __init__(self, n):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n, 128),
            nn.BatchNorm1d(128),
            nn.ReLU(),
            nn.Linear(128, 64),
            nn.BatchNorm1d(64),
            nn.ReLU(),
            nn.Linear(64, 10)
        )

    def forward(self, X):
        return self.net(X)

In [60]:
lr = 0.01
epochs = 200

In [61]:
net = ANN(X_train.shape[1])
# device = 'mps'
# net = net.to(device)
crit = nn.CrossEntropyLoss()
optimizer = torch.optim.SGD(net.parameters(), lr = lr, weight_decay = 0.0001)

In [62]:
net.parameters

<bound method Module.parameters of ANN(
  (net): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=64, out_features=10, bias=True)
  )
)>

In [63]:
for epoch in range(epochs):
    for batch_X, batch_y in train_load:
        #data to gpu
        # batch_X = batch_X.to(device)
        # batch_y = batch_y.to(device)

        #fwd
        y = net(batch_X)
        
        #loss
        loss = crit(y, batch_y)
        #back
        optimizer.zero_grad()
        loss.backward()
        #update param
        optimizer.step()
    print(f'epoch: {epoch + 1}, loss is:  {loss}')

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)


epoch: 1, loss is:  1.3048208951950073
epoch: 2, loss is:  1.0512317419052124
epoch: 3, loss is:  0.919634997844696
epoch: 4, loss is:  0.8234858512878418
epoch: 5, loss is:  0.7354304790496826
epoch: 6, loss is:  0.6906117796897888
epoch: 7, loss is:  0.6402059197425842
epoch: 8, loss is:  0.6152352690696716
epoch: 9, loss is:  0.6263336539268494
epoch: 10, loss is:  0.5585490465164185
epoch: 11, loss is:  0.5450193285942078
epoch: 12, loss is:  0.526728093624115
epoch: 13, loss is:  0.5092233419418335
epoch: 14, loss is:  0.4816353917121887
epoch: 15, loss is:  0.4960978329181671
epoch: 16, loss is:  0.49509790539741516
epoch: 17, loss is:  0.46825718879699707
epoch: 18, loss is:  0.4441409707069397
epoch: 19, loss is:  0.45402657985687256
epoch: 20, loss is:  0.40447884798049927
epoch: 21, loss is:  0.40315955877304077
epoch: 22, loss is:  0.43916183710098267
epoch: 23, loss is:  0.4179874062538147
epoch: 24, loss is:  0.4159972369670868
epoch: 25, loss is:  0.3996221125125885
epoch

In [64]:
net.eval()

ANN(
  (net): Sequential(
    (0): Linear(in_features=784, out_features=128, bias=True)
    (1): BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): ReLU()
    (3): Linear(in_features=128, out_features=64, bias=True)
    (4): BatchNorm1d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (5): ReLU()
    (6): Linear(in_features=64, out_features=10, bias=True)
  )
)

In [67]:
# device = torch.device('mps')
with torch.no_grad():
    total_loss = 0
    for batch_X, batch_y in test_load:
        # batch_X = batch_X.to(device)
        # batch_y = batch_y.to(device)
        y = net(batch_X)
        loss = crit(y, batch_y)
        total_loss += loss
avg_loss = total_loss / (len(test_load))
print(avg_loss)

tensor(0.4224)


/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)


In [69]:
df2['label'].value_counts()

label
2    6000
9    6000
6    6000
0    6000
3    6000
4    6000
5    6000
8    6000
7    6000
1    6000
Name: count, dtype: int64

# Hyperparameter tuning (Optuna)

In [85]:
class NNH(nn.Module):
    def __init__(self, input_dim, output_dim, num_hidden, neurons):
        super().__init__()

        layers = []
        for i in range(num_hidden):
            layers.append(nn.Linear(input_dim, neurons))
            layers.append(nn.BatchNorm1d(neurons))
            layers.append(nn.ReLU())
            layers.append(nn.Dropout(0.2))
            input_dim = neurons
        layers.append(nn.Linear(neurons, output_dim))

        self.model = nn.Sequential(*layers)

    def forward(self, X):
        return self.model(X)

In [100]:
def obj(trial):
    
    # next hyperparams
    num_hidden = trial.suggest_int("num_hidden", 1, 5)
    neurons = trial.suggest_int("num_neurons", 8, 128, step = 8)
    # model init
    input_dim = 784
    output_dim = 10

    model = NNH(input_dim, output_dim, num_hidden, neurons)
    
    # params init
    lr = 0.1
    epochs = 100
    # optim selection
    crit = nn.CrossEntropyLoss()
    optimizer = torch.optim.SGD(model.parameters())
    # train loop
    for epoch in range(epochs):
        for batch_X, batch_y in train_load:
            #data to gpu
            # batch_X = batch_X.to(device)
            # batch_y = batch_y.to(device)
    
            #fwd
            y = net(batch_X)
            
            #loss
            loss = crit(y, batch_y)
            #back
            optimizer.zero_grad()
            loss.backward()
            #update param
            optimizer.step()

    # eval
    model.eval()
    total = 0
    correct = 0
    with torch.no_grad():
        for batch_X, batch_y in test_load:
            outputs = model(batch_X)
            _, predicted = torch.max(outputs, 1)
            total = total + batch_y.shape[0]
            correct = correct + (predicted == batch_y).sum().item()
            accuracy = correct / total
    
    return accuracy

In [101]:
import optuna

study = optuna.create_study(direction = "maximize")

[I 2026-06-06 14:13:27,331] A new study created in memory with name: no-name-7dbf0be5-fab3-4a05-bfb0-d26ccea5da9f


In [102]:
study.optimize(obj, n_trials = 10)

/opt/anaconda3/lib/python3.13/site-packages/torch/utils/data/dataloader.py:692: UserWarning: 'pin_memory' argument is set as true but not supported on MPS now, device pinned memory won't be used.
  warnings.warn(warn_msg)
[I 2026-06-06 14:13:40,750] Trial 0 finished with value: 0.09891666666666667 and parameters: {'num_hidden': 5, 'num_neurons': 72}. Best is trial 0 with value: 0.09891666666666667.
[I 2026-06-06 14:13:53,662] Trial 1 finished with value: 0.09816666666666667 and parameters: {'num_hidden': 5, 'num_neurons': 48}. Best is trial 0 with value: 0.09891666666666667.
[I 2026-06-06 14:14:06,594] Trial 2 finished with value: 0.10316666666666667 and parameters: {'num_hidden': 1, 'num_neurons': 48}. Best is trial 2 with value: 0.10316666666666667.
[I 2026-06-06 14:14:19,645] Trial 3 finished with value: 0.09816666666666667 and parameters: {'num_hidden': 5, 'num_neurons': 48}. Best is trial 2 with value: 0.10316666666666667.
[I 2026-06-06 14:14:32,776] Trial 4 finished with value: 0